/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayones;

/**
 *
 * @author Hajime
 */
public class frame2 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboMonth = new javax.swing.JComboBox<>();
        TextFood = new javax.swing.JTextField();
        TextYear = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        TextHousing = new javax.swing.JTextField();
        TextUtilities = new javax.swing.JTextField();
        TextTransportation = new javax.swing.JTextField();
        TextEducation = new javax.swing.JTextField();
        TextMedic = new javax.swing.JTextField();
        TextRecreation = new javax.swing.JTextField();
        TextOther = new javax.swing.JTextField();
        TextIncome = new javax.swing.JTextField();
        KERJO = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        TombolProcess = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ComboMonth.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        ComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "Desember" }));
        ComboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMonthActionPerformed(evt);
            }
        });
        getContentPane().add(ComboMonth);
        ComboMonth.setBounds(150, 50, 150, 30);

        TextFood.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextFood);
        TextFood.setBounds(290, 200, 210, 30);

        TextYear.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextYear);
        TextYear.setBounds(420, 50, 100, 30);

        jTextField3.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(420, 50, 100, 30);

        TextHousing.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextHousing);
        TextHousing.setBounds(290, 260, 210, 30);

        TextUtilities.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextUtilities);
        TextUtilities.setBounds(290, 310, 210, 30);

        TextTransportation.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextTransportation);
        TextTransportation.setBounds(290, 370, 210, 30);

        TextEducation.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextEducation);
        TextEducation.setBounds(290, 420, 210, 30);

        TextMedic.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextMedic);
        TextMedic.setBounds(290, 480, 210, 30);

        TextRecreation.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextRecreation);
        TextRecreation.setBounds(290, 530, 210, 30);

        TextOther.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextOther);
        TextOther.setBounds(290, 580, 210, 30);

        TextIncome.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextIncome);
        TextIncome.setBounds(290, 100, 210, 30);

        KERJO.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        KERJO.setForeground(new java.awt.Color(255, 255, 0));
        KERJO.setText("-");
        getContentPane().add(KERJO);
        KERJO.setBounds(710, 90, 260, 30);

        NAMA.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        NAMA.setForeground(new java.awt.Color(255, 255, 0));
        NAMA.setText("-");
        getContentPane().add(NAMA);
        NAMA.setBounds(690, 50, 260, 30);

        TombolProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/PROCESS.jpg"))); // NOI18N
        TombolProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolProcessActionPerformed(evt);
            }
        });
        getContentPane().add(TombolProcess);
        TombolProcess.setBounds(380, 650, 110, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/EXIT.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 650, 110, 50);

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/FRAME1.jpg"))); // NOI18N
        BACKGROUND.setText("jLabel1");
        BACKGROUND.setPreferredSize(new java.awt.Dimension(1024, 768));
        BACKGROUND.setRequestFocusEnabled(false);
        getContentPane().add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMonthActionPerformed

    private void TombolProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolProcessActionPerformed
        // TODO add your handling code here:
        
        
        frame3 call = new frame3 ();
        call.setExtendedState(frame3.MAXIMIZED_BOTH);
        call.setVisible(true);
        this.setVisible(false);
        
        
        call.FOODCREDIT.setText(TextFood.getText());
        call.HOUSINGCREDIT.setText(TextHousing.getText());
        call.UTILITIESCREDIT.setText(TextUtilities.getText());
        call.TRANSPORTCREDIT.setText(TextTransportation.getText());
        call.EDUCATIONCREDIT.setText(TextEducation.getText());
        call.MEDICCREDIT.setText(TextMedic.getText());
        call.RECREATIONCREDIT.setText(TextRecreation.getText());
        call.OTHERCREDIT.setText(TextOther.getText());
        
       
        call.INCOMEDEBIT.setText(TextIncome.getText());
        call.TahunBre.setText(TextYear.getText());
        String bulan;
        bulan = (String)ComboMonth.getSelectedItem();
        call.BULAN.setText(bulan);
        
        
        int food, housing, utilities, transportation,totalSPEND, 
        education, medic, recreation, other, remain, income;//deklarasi tipe data variabel
        
        
        income = Integer.parseInt(TextIncome.getText());
        food = Integer.parseInt(TextFood.getText());//inisialisasi value dari masing-masing variabel
        housing = Integer.parseInt(TextHousing.getText());
        utilities = Integer.parseInt(TextUtilities.getText());
        transportation = Integer.parseInt(TextTransportation.getText());
        education = Integer.parseInt(TextEducation.getText());
        medic = Integer.parseInt(TextMedic.getText());
        recreation = Integer.parseInt(TextRecreation.getText());
        other = Integer.parseInt(TextOther.getText());
        
        totalSPEND = food + housing + utilities + transportation + education + medic + recreation + other;
        String SPENDtotal=Integer.toString(totalSPEND);
        int sisacuy=income-totalSPEND;
        String sisa=Integer.toString(sisacuy);
        call.TOTALCREDIT.setText(SPENDtotal);
        call.TOTALDEBIT.setText(TextIncome.getText());
        if(totalSPEND<income){
            
            call.HEADER.setText("Congratulations!");
            call.HasilAkhir.setText(sisa + "  Surplus!");
        }
        else{
            call.HEADER.setText("Unfortunately!");
            call.HasilAkhir.setText(sisa + "  Deficit! Check our tips.");
        }
        
        
        
        
    }//GEN-LAST:event_TombolProcessActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    public static javax.swing.JComboBox<String> ComboMonth;
    public static javax.swing.JLabel KERJO;
    public static javax.swing.JLabel NAMA;
    public static javax.swing.JTextField TextEducation;
    public static javax.swing.JTextField TextFood;
    public static javax.swing.JTextField TextHousing;
    public static javax.swing.JTextField TextIncome;
    public static javax.swing.JTextField TextMedic;
    public static javax.swing.JTextField TextOther;
    public static javax.swing.JTextField TextRecreation;
    public static javax.swing.JTextField TextTransportation;
    public static javax.swing.JTextField TextUtilities;
    public static javax.swing.JTextField TextYear;
    private javax.swing.JButton TombolProcess;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
