/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayones;

/**
 *
 * @author Hajime
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldNama = new javax.swing.JTextField();
        TextFieldPekerjaan = new javax.swing.JTextField();
        ButtonStart = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TextFieldNama.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextFieldNama);
        TextFieldNama.setBounds(380, 310, 330, 40);

        TextFieldPekerjaan.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        getContentPane().add(TextFieldPekerjaan);
        TextFieldPekerjaan.setBounds(380, 390, 330, 40);

        ButtonStart.setBackground(new java.awt.Color(0, 0, 0));
        ButtonStart.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        ButtonStart.setForeground(new java.awt.Color(255, 255, 0));
        ButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/start button.jpg"))); // NOI18N
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonStart);
        ButtonStart.setBounds(463, 480, 130, 50);

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/login page.jpg"))); // NOI18N
        getContentPane().add(BACKGROUND);
        BACKGROUND.setBounds(0, -50, 1090, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        // TODO add your handling code here:  
        frame2 Panggil = new frame2();
        Panggil.setExtendedState(frame2.MAXIMIZED_BOTH);
        Panggil.setVisible(true);
        this.setVisible(false);
        String namakamu = TextFieldNama.getText();
        Panggil.NAMA.setText(namakamu);
        Panggil.KERJO.setText(TextFieldPekerjaan.getText());
    }//GEN-LAST:event_ButtonStartActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame1 blue = new frame1 ();
                blue.setExtendedState(frame1.MAXIMIZED_BOTH);
                blue.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton ButtonStart;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldPekerjaan;
    // End of variables declaration//GEN-END:variables
}
