/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayones;

/**
 *
 * @author Hajime
 */
public class frame3 extends javax.swing.JFrame {

    /**
     * Creates new form frame3
     */
    public frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INCOMECREDIT = new javax.swing.JLabel();
        FOODDEBIT = new javax.swing.JLabel();
        HOUSINGDEBIT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TOTALDEBIT = new javax.swing.JLabel();
        FOODCREDIT = new javax.swing.JLabel();
        HOUSINGCREDIT = new javax.swing.JLabel();
        UTILITIESCREDIT = new javax.swing.JLabel();
        TRANSPORTCREDIT = new javax.swing.JLabel();
        EDUCATIONCREDIT = new javax.swing.JLabel();
        MEDICCREDIT = new javax.swing.JLabel();
        RECREATIONCREDIT = new javax.swing.JLabel();
        OTHERCREDIT = new javax.swing.JLabel();
        TOTALCREDIT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BULAN = new javax.swing.JLabel();
        TahunBre = new javax.swing.JLabel();
        INCOMEDEBIT = new javax.swing.JLabel();
        HEADER = new javax.swing.JLabel();
        HasilAkhir = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        INCOMECREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        INCOMECREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INCOMECREDIT.setText("-");
        INCOMECREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(INCOMECREDIT);
        INCOMECREDIT.setBounds(560, 200, 210, 30);

        FOODDEBIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        FOODDEBIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FOODDEBIT.setText("-");
        FOODDEBIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(FOODDEBIT);
        FOODDEBIT.setBounds(310, 240, 210, 30);

        HOUSINGDEBIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        HOUSINGDEBIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOUSINGDEBIT.setText("-");
        HOUSINGDEBIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(HOUSINGDEBIT);
        HOUSINGDEBIT.setBounds(310, 290, 210, 30);

        jLabel4.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 340, 210, 30);

        jLabel5.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 380, 210, 30);

        jLabel6.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 430, 210, 30);

        jLabel7.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 480, 210, 30);

        jLabel8.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("-");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 520, 210, 30);

        jLabel9.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("-");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 570, 210, 30);

        TOTALDEBIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        TOTALDEBIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TOTALDEBIT.setText("-");
        TOTALDEBIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TOTALDEBIT);
        TOTALDEBIT.setBounds(310, 620, 210, 30);

        FOODCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        FOODCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FOODCREDIT.setText("-");
        FOODCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(FOODCREDIT);
        FOODCREDIT.setBounds(560, 240, 210, 30);

        HOUSINGCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        HOUSINGCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOUSINGCREDIT.setText("-");
        HOUSINGCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(HOUSINGCREDIT);
        HOUSINGCREDIT.setBounds(560, 290, 210, 30);

        UTILITIESCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        UTILITIESCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UTILITIESCREDIT.setText("-");
        UTILITIESCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(UTILITIESCREDIT);
        UTILITIESCREDIT.setBounds(560, 340, 210, 30);

        TRANSPORTCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        TRANSPORTCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TRANSPORTCREDIT.setText("-");
        TRANSPORTCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TRANSPORTCREDIT);
        TRANSPORTCREDIT.setBounds(560, 380, 210, 30);

        EDUCATIONCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        EDUCATIONCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EDUCATIONCREDIT.setText("-");
        EDUCATIONCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EDUCATIONCREDIT);
        EDUCATIONCREDIT.setBounds(560, 430, 210, 30);

        MEDICCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        MEDICCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MEDICCREDIT.setText("-");
        MEDICCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MEDICCREDIT);
        MEDICCREDIT.setBounds(560, 480, 210, 30);

        RECREATIONCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        RECREATIONCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RECREATIONCREDIT.setText("-");
        RECREATIONCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(RECREATIONCREDIT);
        RECREATIONCREDIT.setBounds(560, 520, 210, 30);

        OTHERCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        OTHERCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OTHERCREDIT.setText("-");
        OTHERCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(OTHERCREDIT);
        OTHERCREDIT.setBounds(560, 570, 210, 30);

        TOTALCREDIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        TOTALCREDIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TOTALCREDIT.setText("-");
        TOTALCREDIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TOTALCREDIT);
        TOTALCREDIT.setBounds(560, 620, 210, 30);

        jLabel2.setFont(new java.awt.Font("Candara", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 50, 200, 70);

        BULAN.setFont(new java.awt.Font("Candara", 3, 48)); // NOI18N
        BULAN.setForeground(new java.awt.Color(255, 255, 0));
        BULAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BULAN.setText("-");
        getContentPane().add(BULAN);
        BULAN.setBounds(40, 50, 260, 70);

        TahunBre.setFont(new java.awt.Font("Candara", 3, 48)); // NOI18N
        TahunBre.setForeground(new java.awt.Color(255, 255, 0));
        TahunBre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TahunBre.setText("-");
        getContentPane().add(TahunBre);
        TahunBre.setBounds(320, 50, 200, 70);

        INCOMEDEBIT.setFont(new java.awt.Font("Candara", 0, 26)); // NOI18N
        INCOMEDEBIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INCOMEDEBIT.setText("-");
        INCOMEDEBIT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(INCOMEDEBIT);
        INCOMEDEBIT.setBounds(310, 200, 210, 30);

        HEADER.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        HEADER.setForeground(new java.awt.Color(255, 255, 0));
        HEADER.setText("-");
        getContentPane().add(HEADER);
        HEADER.setBounds(640, 670, 180, 40);

        HasilAkhir.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        HasilAkhir.setForeground(new java.awt.Color(255, 255, 0));
        HasilAkhir.setText("-");
        getContentPane().add(HasilAkhir);
        HasilAkhir.setBounds(660, 710, 350, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/IDE.jpg"))); // NOI18N
        jButton1.setToolTipText("Get some useful tips");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(830, 200, 160, 170);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/EXIT.jpg"))); // NOI18N
        jButton2.setToolTipText("Exit program");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 550, 110, 50);

        jLabel10.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("You're");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(580, 710, 70, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/RETRY.jpg"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(850, 440, 140, 50);

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mayones/frame3.jpg"))); // NOI18N
        getContentPane().add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame4 skuy = new frame4();
        skuy.setExtendedState(frame4.MAXIMIZED_BOTH);
        skuy.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        frame1 lagi = new frame1();
        lagi.setExtendedState(frame1.MAXIMIZED_BOTH);
        lagi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    public static javax.swing.JLabel BULAN;
    public static javax.swing.JLabel EDUCATIONCREDIT;
    public static javax.swing.JLabel FOODCREDIT;
    public static javax.swing.JLabel FOODDEBIT;
    public static javax.swing.JLabel HEADER;
    public static javax.swing.JLabel HOUSINGCREDIT;
    public static javax.swing.JLabel HOUSINGDEBIT;
    public static javax.swing.JLabel HasilAkhir;
    public static javax.swing.JLabel INCOMECREDIT;
    public static javax.swing.JLabel INCOMEDEBIT;
    public static javax.swing.JLabel MEDICCREDIT;
    public static javax.swing.JLabel OTHERCREDIT;
    public static javax.swing.JLabel RECREATIONCREDIT;
    public static javax.swing.JLabel TOTALCREDIT;
    public static javax.swing.JLabel TOTALDEBIT;
    public static javax.swing.JLabel TRANSPORTCREDIT;
    public static javax.swing.JLabel TahunBre;
    public static javax.swing.JLabel UTILITIESCREDIT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
